apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myvote
  name: myvote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myvote
  template:
    metadata:
      labels:
        app: myvote
    spec:
      containers:
      - image: dockersamples/examplevotingapp_vote
        name: myvote
        ports:
        - containerPort: 80
          name: myvote
